import NewsLetterRegistration from "@/component/comment/NewsLetterRegistration/NewsLetterRegistration";
import Header from "@/component/header/Header";
import classes from "./event.module.css";


export const metadata = {
    title: "This is event module",
    description: "Generated by create next app",
  };
  
  export default function EventLayout({
    children,
  }) {
    return (
      <body className={classes.event}>
        <Header />
        <NewsLetterRegistration />
        {children}
      </body>
    );
  }